name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MICROFRONTEND_CB52F }}'
          entryPoint: "./packages/auth"
          channelId: 'auth'
          projectId: microfrontend-cb52f
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels